### PR TITLE
cmake/CFeatureCheck.cmake: fix feature tests failing when Opus is a submodule

### PR DESCRIPTION
**Pull request by davidebeatrici**
xiph/opus#182

### CODE REVIEW

**Comment by xnorpx** [comment]
Should these also be changed?

rg CMAKE_SOURCE_DIR
CMakeLists.txt
491:  configure_package_config_file(${CMAKE_SOURCE_DIR}/cmake/OpusConfig.cmake.in

cmake\OpusConfig.cmake
8:configure_file(${CMAKE_SOURCE_DIR}/cmake/config.h.cmake.in config.h @ONLY)

cmake\OpusFunctions.cmake
69:  if(EXISTS "${CMAKE_SOURCE_DIR}/package_version")

**Comment by davidebeatrici** [comment]
Yes.

**Comment by xnorpx** [comment]
can you add that to this change?

**Comment by davidebeatrici** [comment]
Wouldn't it be better if I do it in another pull request?

**Comment by xnorpx** [comment]
Would be nice to have same type of change in one commit.

**Comment by davidebeatrici** [comment]
This pull request focuses on getting Opus to build correctly when it's added a submodule, the instances of `CMAKE_SOURCE_DIR` you found don't cause a CMake error.

I would prefer to create a separate pull request to replace `CMAKE_SOURCE_DIR` everywhere.

**Comment by xnorpx** [comment]
ok sure

**Comment by xnorpx** [comment]
@davidebeatrici I added the patch to the latest set of patches but waiting for signoff from @mark4o

**Comment by davidebeatrici** [comment]
Excellent!

**Pull request merged**
